### ISSUE TITLE
MarketCapBot - Automate Twitter posting

### ISSUE THREAD

**Issue by sofiasedlova** [1712n/twitter-bot-challenge#8]
The goal of this challenge is to build a Python [Twitter bot](https://twitter.com/CryptoCapBot) using GitHub Actions and MongoDB.

## Required functionality

A Python function will compose and post a tweet with the latest values from [MongoDB time series](https://www.mongodb.com/docs/manual/core/timeseries-collections/) collections using the logic described below.

## Algo

1. query `ohlcv_db` for the top 100 `pair`s by compound `volume`
1. query `posts_db` for the latest documents corresponding to those 100 `pair`s
1. sort results by the oldest `timestamp` to find the pairs that haven't been posted for a while, then corresponding `volume` to find the biggest markets among them and select the `pair_to_post`
1. compose `message_to_post` for the `pair_to_post` with corresponding latest `volume`s by `market` values from `ohlcv_db` using this example:
   ```
   Top Market Venues for BTC-USDC:
   Binance 30.10%
   Coinbase 20.20%
   Kraken 10.30%
   Bitstamp 5.40%
   Huobi 2.50%
   Others 31.5%
   ```
1. keep similar tweets in one thread. if `pair_to_post` tweets already exists in `posts_db`, post tweet to the corresponding Twitter thread. else, post a new tweet.
1. add your `message_to_post` to `posts_db`

## Important notes

- **Send your resume and a link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org). Then we'll add you to collaborators and share all necessary credentials.**
- Create your own branch in this [repository](https://github.com/1712n/twitter-bot-challenge#twitter-bot-challenge) and use iterative approach. We want to see your progress as much as we want to see the result.
- Think about tests and error handling. We will be stress testing your code by corrupting databases and revoking access permissions.
- Limit Twitter API usage, rely on MongoDB to save the state.
- Leverage MongoDB time series optimizations to save computational resources.

As soon as we get a good enough solution from a candidate, we start the interviewing process. If you are ready with your branch - create a pull request and assign it to @sofiasedlova and @darknessest for review.

**Comment by yeboahd24** [comment]
Please is the database name called `metrics` when I print the databases I am getting that but when I tried to list tables I am getting an unauthorized error.

**Comment by yeboahd24** [comment]
I am having an issue with the Twitter API can you please check it for me? the error below is what I am getting.

`You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here`: [link](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve)

**Comment by sofiasedlova** [comment]
@yeboahd24 we've tested the credentials on our side, and everything is fine.

**Comment by yeboahd24** [comment]
> @yeboahd24 we've tested the credentials on our side, and everything is fine.

Yeah I am not saying is not working what I am trying to say is that I am getting the error as stated above you can try to run the script and see what I am talking about.

**Comment by sofiasedlova** [comment]
Hey guys! It was a pleasure to see considerable attention to our Challenge Program and this Python task specifically.

Throughout this round, more than 60 users were added as outside collaborators, 30+ branches were created, 17 pull requests were reviewed. You have differently approached this problem using elegant aggregations, showing off OOP native style and unit tests.

Let me announce the winner of the challenge. The most pythonic solution was submitted by @eg-mart! 🧠
